### ISSUE TITLE
library not found -lBaiduMapApi

### ISSUE THREAD

**Issue by RockerHX** [iosmvn/BaiduMap-iOS-SDK#1]
用cocoapods更新到2.8.1编译提示library not found -lBaiduMapApi

**Comment by danfeng** [comment]
我测试没问题,
1、更新到2.8.1.1，然后确保工程中有.mm文件；
2、参考下使cocopods管理开源库编译出现Library not found for -lPods问题的解决方法 http://blog.sina.com.cn/s/blog_67d955460101xbuh.html
3、上面都不能解决，麻烦你新建一个demo测试下，要是还有问题邮件发我。

**Comment by RockerHX** [comment]
我现在有点怀疑是cocoapods问题，我用的0.38.0版本，刚没升级两天，你用的0.37.2吗？

**Comment by RockerHX** [comment]
确认了，是版本问题，0.38.0，需要删除Other Linker Flags里的BaiduMapApi项
