### ISSUE TITLE
请问我跑起来项目，为什么地图界面什么也看不到？只有网格

### ISSUE THREAD

**Issue by luxuelin** [iosmvn/BaiduMap-iOS-SDK#3]

**Comment by danfeng** [comment]
检查下：1、 key有木有设置正确，与Bundle identifier对应。   BOOL ret = [_mapManager start:@"please enter your key" generalDelegate:self];
2、项目-Info.plist文件，添加App Transport Security Settings - Allow Arbitrary Loads，值为YES；
